name: Pnpm lock generate
on: pull_request
permissions:
  contents: write
  pull-requests: write

jobs:
  pnpm-lock-autogenerate:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Auto generate pnpm lock yaml
        if: contains(steps.changed-files.outputs.all_changed_files, 'package-lock.json')
        run: |
          echo "cleaning recent node_modules and lock file..."
          rm -rf node_modules/
          rm -rf pnpm-lock.yaml
          pnpm install

      - name: Commit and Push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; 
          then 
            echo "committing..."
            git config --global user.name 'auto-generate-bot'
            git config --global user.email 'auto-generate-bot@adevinta.com'
            git commit -am "chore(autogenerated): pnpm package lock file"
            git push
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ref: ${{ github.event.pull_request.head.ref }}
